# Generated by Django 4.0.5 on 2022-06-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserMaps',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_maps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Maps',
            fields=[
                ('map_id', models.AutoField(primary_key=True, serialize=False)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('nome_cidade', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'maps',
                'managed': False,
            },
        ),
    ]
